---
title: "Reading notes"
---

# Mallet 2013

- 

# Foote 2018

- Sympatric speciation does not involve physical/geographic barriers, so offers insights into role of selection (natural and sexual) in driving speciation.
- This speciation (divergence with gene flow) is therefore rare, extreme, restrictive, and controversial.
- Genomic methods have provided evidence of two kinds: either multiple colonisations and secondary contact, or actual sympatric divergence.
- Author overall argues for less focus on primary vs secondary contact as driving speciation, and more on mechanistic aspects of genomic architecture.
- Previous methods used phylogenetics to infer sympatric speciation from monophyly, but monophyly is not a good indicator of sympatric speciation (consistent with, but not exclusive to). (One flaw of Coyne & Orr's criteria.)
- Backwards-in-time approaches are limited to identifying gene flow events arising through coalescence. They cannot distinguish between periods of spatial isolation and of spatial overlap with on gene flow. 
- In cases of actual sympatric speciation, we expect barrier loci to be clustered tightly (close together) in the genome, and at areas of low recombination, and to have a "large effect" especially affecting both reproductive isolation and ecological adaptation. That is, *linkage* or *pleiotropy*. Otherwise, ongoing gene flow (recombination, genome-wide homogenisation) would make it difficult for divergence.
- Modern genomic methods are still biased towards disproving (and not supporting) primary sympatric speciation. Palaeogenomics is a useful tool to tackle this. 
- Author argues that focus should be placed on sympatric speciation, and away from primary vs secondary.
    
# Discussion: Geography of speciation

## Coathup et al 2024

- Theory says sympatric speciation facilitated by magic traits which might be encoded by pleiotropic genes, but little evidence exists of sympatric speciation and empirical evidence of magic traits is rare. Authors investigated role of pleitropy in *Howea* speciation. They found multiple genes showing adaptive divergence between the sister species (sign of pleiotropy, in soil stress tolerance and flowering time). 
- Alternative to magic traits/pleiotropy driving sympatric ecological speciation is linkage disequilibrium. (i.e., one allele with multiple effects vs two close alleles not separated in recombination.) In either case, "major effect loci".
- Dunning et al 2016 and Osborne et al 2019 assessed gene expression and genetic divergence. They identified candidate pleiotropic speciation genes. The current study aimed to test whether these genes actually are pleiotropic loci affecting soil stress tolerance and flowering time. If so, this would be positive evidence for magic traits. 
- Method: T-DNA knockout *A. thaliana* used for high-throughput phenotyping (knockouts in orthologues of candidate speciation genes, 11 knockout mutants).
    - Grown under various stress emulating Lord Howe Island. Then morphology, stress responses and flowering time measured. 
- Five genes potential speciation genes: knockouts in each of these showed displaced flowering times and altered soil stress response (cadmium, drought, salt). Largest effect sizes in SAL1 (latest flowering) and SIZ1 (earliest flowering)
    - Knockout of SIZ1 caused reduced drought tolerance. *H. belmoreana* has lower expression of the two SIZ1 homologues and also cannot colonise calcareous soils. On the other hand, knockout of SAL1 caused increased drought tolerance (consistent with *H. forsteriana*), but reduced salt tolerance which doesn't match with *Howea* scenario---so less evidence for this locus driving sympatric speciation cf SIZ1.
- Robust example of genetic architecture of sympatric speciation. Evidence of pleiotropy in multiple loci, so could be a combination of pleiotropy and linkage disequilibrium.

How did knockout (removal) give these results? Counterintuitive?

## Dean et al 2019

- An assumption when considering sympatric species pairs is that they originated from a recent, genetically homogenous ancestor, but most evidence invokes introgression/admixture upon secondary contact as responsible for speciation. The authors compare two ecotypes of three-spined stickleback (no, multiple species-pairs?) using morphological data, targeted genotyping and genome-wide SNP data. 
    - The two ecotypes show extensive hybridisation in sympatry/parapary.
    - There are rare cases of complete reproductive isolation in sticklebacks, but these cases involve ancient allopatric origins.
- Importance of genetic admixture upon secondary contact widely known in plants since 1970s, but has also started gaining popularity in animals. 
    - Classic examples like Darwin's finches, Lake Victoria cichlids and *Anopheles* species complex all either involved genetic admixture events or are cryptic cases of homoploid hybrid speciation.
- Overwhelming evidence for ancient allopatry, and against "true" sympatric ecological speciation. (And authors found the same.)
- They find that the two ecotypes are strongly reproductively isolated, but also a complex colonisation history suggesting admixture upon secondary contact in addition to disruptive ecological selection (i.e., older allopatric origin). 
- Three hypotheses (none consider sympatric speciation option? wait, the first classic one probably is)
- Compelling morphological and genetic evidence of unusually strong reproductive isolation between lagoon resident and anadromous stickleback, in spite of (low) gene flow. Classic purely-ecological speciation model (relative sea level change) unlikely; at least two colonisation and therefore admixture upon secondary contact (alongside strong selection for maintenance of differentiation, i.e. partial ecological basis)
- Reproductive isolation in this island species-pair example is considerably stronger than most other stickleback examples, so this could potentially be a very useful system to work further on these questions.
- Also evidence against "linear, bifurcating process" model.

Species pairs? Or just ecotypes? Confusing.

# Rundle & Nosil 2005

- Renewed interest in microevolutionary processes driving macroevolutionary speciation was linked to reclassficiation of speciation models from geographic scheme (sympatry vs allopatry) to focus on reproductive isolation.
- Barriers as a result of ecologically driven divergent selection
- Ecological speciation different from other models that focus on chance events (polyploidisation, hybridisation, genetic drift, founder events, population bottlenecks), or on non-divergent and/or non-ecological selection (runaway selection, sexual conflict)

## Ecological causes of divergent selection

Environmental differences, sexual selection, ecological interactions

# Discussion: Pre-zygotic isolation

## Zhang et al 2024

- Role of ecology and geography have not been explored much at later stages of speciation, because traditionally focus on role of ecology in *initiating* speciation and on role of geography (reinforcement) on species pairs lacking divergent characteristics.
- How divergent ecology interacts with geography to affect RI in later stages of speciation remains unclear
- Reinforcement: increased favour towards prezygotic isolation in sympatry, peripatry or parapatry, due to fitness cost to hybridisation
- Increased habitat isolation can also arise from direct selection against immigrants (high fidelity to native environment favoured)
- Three gall wasps in genus *Belonocnema*, specific to *Quercus* hosts.
- Existing knowledge: two sympatric wasp species are in later stages of speciation
- Test: in allopatry, does host plant divergence yield higher RI? In host plant divergence, does sympatry yield higher RI than allopatry (due to selection for reduced migration and reduced hybridisation)?
- Measured "degree of sexual isolation in the absence of host plant"
- Natural temporal difference in the wasp species, so they stored some galls at 4 dec C for one week which delayed the emergence. Adults were used in experiments 1-2 days after emergence. 
- Measured host plant selection using a controlled two-choice experiment, using females instead of males (female host choice determines environment for next generation, and males display lower host fidelity). 
    - Female aspirated into the container and observed for 30 min at 2-min intervals (15 obs), with the assumption that time spent on host plant is correlated with oviposition decision.
    - Calculated proportion of time spent on natal plant ($[0, 1]$), compared using GLMM.
    - Also calculated pairwise estimates of host plant preference difference: absolute difference between preference values calculated above (also $[0, 1]$).
- Measured sexual isolation by observing courtship and mating interactions between males and females, using controlled no-choice preference trials.
    - Male and female (same or different species) aspirated into container, observed for same time, and recorded three interactions: male wing buzzing/fanning, male mounting female, copulation.
    - Calculated probability of mating between conspecific and heterospecific pairs, and compared using GLMM.
    - Comparison between species pair type and individual pair cannot be done using GLMM, so they also calculated strength of sexual isolation between species pairs using a formula.
- Evidence that host use (ecological) interacts with geography in driving divergent selection in *Belonocnema* wasps.
    - Sympatric wasp species with different host plant showed highest habitat isolation, while allopatric with same host plant showed lowest.
    - Proximity to two host plant options increased host preference (Petri dish vs cups)
    - Sympatric also showed highest sexual isolation, while allopatric with same host plant showed lowest.
- High isolation in allopatric species with same host plant suggest that selection is not directly driven by habitat use. Similar selection environment could have taken different phenotypic pathways (mutation-order speciation). 
- Three possible mechanisms for high isolation in sympatric species:
    - Templeton effect/differential fusion: in sympatry, strong isolation is required for isolated populations to persist, whereas weakly isolated populations fuse.
    - Reinforcement: natural selection against hybrids with lower fitness
    - Reproductive interference: presence of sympatric species during mating (or cost of migration) could elevate prezygotic isolation
- Also found asymmetry between habitat isolation and sexual isolation between allopatric species sharing the same host plant: lineage that emigrates more shows stronger habitat isolation (lower fitness of immigrants in alternative habitat) while lineage that receives more immigrants shows stronger sexual isolation (lower fitness of hybrids).
- The three closely related wasp species are a good model for speciation research, due to their unique ecology and geography. Their framework is also useful for exploring completion of speciation, a knowledge gap.

## Schield et al 2024

- How does the genetic basis of sexual selection result in barrier to gene flow in secondary contact?
- Most studies explore links between either sexual traits and reproductive isolation, or genomic divergence and genetic association with sexual traits. Not the full flow from genomic divergence to reproductive isolation via barrier to gene flow.
- For species like Barn Swallow which are early in speciation process, sexual selection may be driving RI at small number of barrier loci involved in sexual traits. 
    - Genetic coupling of barrier loci (linkage disequilibrium) facilitates speciation, via both direct and indirect selection. With increase in coupled barrier loci, barrier to gene flow is stengthened.
    - Coupling is likely to arise in allopatry, and can promote RI upon further secondary contact.
- Barn Swallow populations all diverged recently from the common ancestor about 11 kya, and there is strong evidence for divergent sexual selection among these populations.
    - Not only does the species have multiple populations (subspecies), but there are also multiple hybrid zones, with varying divergence in sexual traits. These hybrid zones allow tests of whether sexual selection results in RI upon secondary contact.
    - Further, two of these hybrid zones also have divergences in nonbreeding migratory route, which is a potential coupled trait (low survival of hybrids taking nonadaptive migratory routes; i.e., hybrid fitness).
    - Explicit tests of effects of trait loci on gene flow are necessary because degree of concordance between allopatric evolutionary processes and hybrid fitness is not clear a priori.
- Do sexual trait loci experience divergent sexual selection in allopatry and promote RI upon secondary contact? Is there LD among barrier loci (sexual traits, migratory route) in secondary contact, mainting RI via effects on hybrid fitness?
- Found that 6 ssp. cluster in 3 groups. Individuals from hybrid zones show intermediate/similar to parent plumage trait values (breast feather colour, tail streamer length) and admixture proportions.
- Prevalence of back-crossed, late generation hybrids, and demographic models, suggest that hybrid zones formed upon secondary contact following allopatry.
- *rustica*-*gutturalis* hybrid zone estimated to have formed 2000 generations ago, while the *tytleri* ones were more recent (< 1000 generations).
- Trait variation is controlled by few loci and not several genes: both traits have high proportion of phenotypic variation explained (PVE) by SNP genotypes, and high proportion of genetic effects (PGE) by small number of SNPs.
- Ventral colour SNPs on chromosome 1A and Z (genes affecting melanogenesis and feathering phenotype), whereas tail streamer length SNPs on chromosome 2 (enzymes with regulatory functions potentially affecting transcription, intracellular transport, growth factor stability).
    - Concentration of ventral colour associations on Z chromosome (sex chromosome) supports that sex linkage is favourable for traits involved in mate choice and sexual isolation.
- Across allopatric populations, sexual trait loci show more genetic differentiation (FST) than do genome-wide comparisons.
    - This could just be due to "background selection" in regions with reduced recombination. However, regions with extremely low recombination rates like centromeres also show higher FST in trait loci---high differentiation in trait loci is due to divergent positive selection rather than background selection alone. Elevated allelic differentitation and extended haplotype homozygosity, also suggest this.
    - Greater fitness effects of ventral colour than tail streamer length.
- Geographic and genomic cline analysis, comparing trait loci--background loci differences across space along the three hybrid zone transects. 
    -Found steeper transition between parental ancestries in trait loci cf background loci. 
    - Steepness itself could arise due to low population density in hybrid zones, but this would show similar clines in trait loci as in other highly differentiated loci (not the case)
    - Stronger selection and barrier to gene flow between *rustica* and other ssp.
    - Cline patterns are weakest in *tytleri*-*gutturalis* hybrid zone, possibly linked to absence of migratory divide between the two populations (though remains to be tested).
- LD arises from hybridisation, but extent of erosion of LD by recombination over generations can be impacted by selection-driven genetic coupling. 
    - They compared interchromosomal LD between trait loci and background loci; if the LD was formed by admixture but not maintained by selection, would find similar levels between the two. But they found much higher LD levels in trait loci.
    - Increase in LD shows consistent differences between hybrid zones, with *rustic* hybrids showing higher.
    - Also no differences in LD between parental populations, therefore admixture important followed by selection.
    - Starting levels of admixture LD higher than current levels, suggesting that selection worked by slowing erosion of LD, rather enhancing LD beyond starting levels.
- Primary/major role of divergent sexual selection in genomic divergence and RI.

# Discussion: Reinforcement

## Bemmels et al 2021

- Dynamics of allopatry initiating speciation, widely accepted. But how sympatry (sec. contact) can complete speciation is contested. 
- RI before secondary contact: either fully complete, or costs to interactions between partially RI species (maladaptive hybridisation) may drive further divergence (reinforcement).
- Problem with complete RI prior to sympatry: takes very long time to evolve, and widepsread occurrence of hybrid zones suggests frequent contact with incomplete RI.
- Alternative is that incipient species interactions change (indirect)---any process that results in divergent character displacement, e.g., divergent agonistic selection to avoid aggressive interactions (though this could result in the opposite, convergence, if interspecific aggression helps defend against true competitors).
- Another option is direct selection for increased RI (direct): reinforcement, i.e., selection to avoid maladaptive hybridisation. Very difficult to demonstrate its existence, so few examples. One of the hallmark indicators of reinforcement is reproductive character displacement (increased divergence in reproductive traits in sympatry than in allopatry), but this can be generated by other processes too. 
- Difficult to determine whether sympatry plays a role in completion of speciation (geographic context difficult to estimate).
- Coalescent demographic modelling, whole-genome datasets. Sympatric E NA *Empidonax* species populations (broad sympatry) show increased RI post secondary contact---unrelated to reproductive character displacement---while western contact zone (narrow sympatry) has lower RI (higher introgression). 
- Methods
    - Whole genome data --> patterns of admixture (is RI higher in broad sympatry than in narrow sympatry?), and patterns of ecological/reproductive character displacement in sympatry. Coalescent modelling --> did geographic contact precede and drive increase in RI?
    - Blood samples --> whole-genome sequencing and genotyping-by-sequencing --> alignment with Willow reference genome, generation of de no Alder genome (linked-read sequencing).
    - Genomic differentiation: weighted Hudson's F_ST_, proportion of genetic ancestry.
    - Geographic contact: GBIF, WorldClim, Maxent SDMs for present climate and LGM. (Potential for range overlap.)
    - Character displacement: morphological measurements of caught birds. Temporal displacement from spring arrival time from eBird.
- Genomes are well differentiated, multiple F_ST_ peaks on most chromosomes, greater in east than west. Similarly, admixture lower in east than west. RI in east not absolute but nearly complete and significantly higher than in west.
- Longer contact in east than in west, south of glaciation. Willow occurred in both but Alder (currently more N breeder) only in east. (However, range overlap in LGM not really in "east", more central [Fig 3].)
- No temporal character displacement. No displacement in bill/body morphology or crown feather reflectance. Only difference in crown colour---subtle, but strongest in UV, but birds unlikely to perceive this difference.
- Support for continuous gene flow even in present day in west, but ceased long after secondary contact in east. However, model support relatively weaker in west (additional complexity).
- Elevated RI could have been due to ecological divergence to avoid resource competition, agonistic selection, or reinforcement---but causal traits elusive.
- Multistage model of speciation: dynamics of initiation and completion of RI have fundamentally different dynamics and drivers.
- Potential alternative reproductive traits that could be under divergent selection: male song, and female preference for male song. Is divergence of male song stronger in sympatry? Is female preference for conspecific song higher in sympatry (reinforcing selection) as in *Ficedule*? Or even gametic level (sperm-related). Also need to explore costs to hybridisation like reduced fitness.
- Their approach is one effective way to study what otherwise remains very difficult, even in non-model systems and species that no longer hybridise.
- Broad sympatry vs narrow sympatry ---> sympatry vs allopatry (not sure if this logical jump is appropriate)

## Levitan & Hao 2025

About postzygotic (gametic) isolation

- How do initially rare reproductive genotypes proliferate over time if they by definition result in reduced mate compatibility?
- External fertilisation --> ease of study, wide variation in intraspecific gametic compatibility.
- Possibility: sexual conflict over fertilisation rate selects for eggs with reduced compatibility, producing population with more than one matched compatibility group. But although this generates variation, not sufficient to explain very low compatibility preventing/limiting hybridisation.
- Two urchin species can produce F1 embryos; *Sd* eggs more susceptible than *Mf*; former can metamorphose into juveniles but magnitudes lower than conspecifics (no introgression between the two species).
- Tested for conspecific sperm precedence (CSP) using no-choice and competitive choice assays. Is variation in hybrid fertilisation related to male and female gamete proteins? Are derived protein variants less likely to result in hybrid fertilisation than ancestral? Do allele frequencies of sperm and egg proteins in sympatry and allopatry support presence of RCD?
- No-choice fertilisation success between conspecific and heterospecific males and females reciprocally. Choice experiments using *Sd* eggs, because it has higher and more variable levels of hybridisation than *Mf*.
- Experiment 1: no-choice + 5 choice (varying heterospecific sperm ratios) crosses. Experiment 2: no-choice + 0.9:0.1 (*Mf*:*Sd*) choice crosses (ability of sperm to fertilise eggs at greatest numerical superiority; more replicates).
- In choice crosses, embryos developed for 3 days then genetic analysis for paternity. Survivorship compared among crosses to test for bias between early postzygotic survivorship (prior to genotyping larvae) and gametic incompatibility.
- *Sd* more susceptible to hybrid fertilisation than *Mf*, and required lower concentration of heterspecific sperm. But presence of conspecific sperm reduced hybridisation---47% no hybridisation even at most extreme ratios favouring hybridisation. Concentration no longer important when both sperm present; instead, relative proportion important.
- Above were overall/average trends, but individual results varied from absolute to nonexistent CSP. This variation was explained by the sperm genotype: presence of shared (ancestral) GG allele increased hybridisation. Higher hybridisation in presence of shared protein was seen also in egg protein, but this was not statistically significant.
- Shared allele more frequent in allopatry than sympatry, but only in eggs and not in sperm bindin (greater cost of egg wastage than sperm wastage).
- Interspecific variation in sperm recognition proteins not enough to fully prevent hybrid fertilisation if given enough time and without competing sperm with higher affinity (conspecifics).
- Likely that reinforcement selection and RCD manifested more in *Mf*.
- Sexual conflict, or generally sexual selection, generates intraspecific variation which then gets acted upon by reinforcement selection.
- Did not like the way this paper was written:
    - Background on the proteins: important info but could have had lay summaries too.
    - Overll just too technical!
    - Results too long, longer than discussion, and contains things that should be in methods (like models and tests)! 
    - Paper should overall have been more inferential, rather than technical reporting.
    
# Discussion: Genetic basis of speciation I

## Turbek et al 2021

- The role of assortative mating (premating isolation), phenotypic traits of species recognition and their genomic basis and origin.
- No ecological barriers yet (and low genomic divergence), but behavioural isolation.
- Viable hybrids are readily formed, indicating lack of genetic incompatibility.
- Post-mating isolation requires longer time in general than pre-mating isolation mechanisms.
- Genomic divergence using shotgun short-read whole-genome sequencing
- PCR amplification for Sanger sequencing of short genomic region having high divergence 
- Choice experiments using song playback and artificial mounts of conspecific and heterospecific males. Used sympatric and ecologically similar heterospecific control.
- Genomic divergence peaks contain plumage colouration genes.
- *Sh* segregating within *Si* at high differentiation sites, suggesting either incomplete lineage sorting or past hybridisation.
- Female colouration largely overlaps between the two species even in avian visual spectrum. 
- Paired males and females showed the same F_ST peaks in whole-genome and double-digest restriction site--associated DNA (ddRAD) sequence data, suggesting lack of hybrid pair formation.
- Although there was high extra-pair mating, candidate fathers and social fathers were of the same species. Social and extra-pair mating maintain assortative mating.
- Genomic differentiation from phylogenies for the whole capuchino radiation suggested recent speciation because there was no species-level monophyly. However, *Si* and other restricted range species formed clades. On the other hand, in phylogenies derived from only the divergence peak regions, it did not form a clade. Although many species shared variants with it at individual peaks, none showed the specific combination (both divergent peaks) of *Si*. This indicates that *Si* phenotype likely arose from standing genetic variation.
- Assortative mating through genetically inherited (plumage, song?) and perhaps culturally inherited (song?) traits, at least early in speciation until subsequent reproductive barriers arise.
- Important divergence peaks are on Z chromosome (large-Z effect).

## Raffini et al 2025

- Inferences about accumulation of RI depend on comparing contemporary populations that are at different stages on a "speciation continuum". Cannot assume a monotic progression from weak to strong isolation.
- Important to distinguish between different stages of RI from differences among taxa
- Compare two ecotypes in same marine snail species, showing similar levels of phenotypic divergence (two ecotypes in both regions), but different levels of genomic divergence (and gene flow/isolation). Parallel speciation.
- The two ecotypes occur close together on many shores and also form contact zones. Spanish (older) and Swedish (younger, after last glaciation).
- Differences between ecotypes have been suggested by several studies, but detailed data combining genome-wide differentiation and spatial coverage of contact zones has been lacking.
- Dense transects across contact zones, low-coverage whole-genome sequences, shell features, behavioural traits.
- Unique: Groups identified/assigned genetically, not based on phenotypic traits.
- Patterns of genomic divergence explored using PCA and DAPC
- Patterns of chromosomal inversion, known to contribute to the differentiation of these two ecotypes, were explored using unthinned datasets. First used Manhattan plots of per-locus F_ST between genetic clusters, with randomisation 1000 times. Genomic inversions differing in frequency between clusters would show higher differentiation than non-inverted regions. Second, used PCAs of linkage map position.
- Some phenotypic traits using standardised image analysis. Cluster analysis and PCA.
- Both regions showed genomic divergence (PCA of SNPs) between ecotypes, but patterns of genetic differentiation between ecotypes were different in the two regions (Sweden more gradual cline, Spain two genetically distinct clusters with no intermediate genotypes and with wave ecotype spatially clustered in low parts of shores). Divergence between Spanish ecotypes larger than divergence among all Swedish.
- Role of chromosomal inversions: Found multiple chromosomal inversions at same sites across countries. Although inversion patterns were congruent between the countries, more pronounced in Spain (higher blocks in Manhattan plots, stronger cluster in PCA).
- Strong phenotypic and behavioural (Crab more wary) divergence between two ecotypes, but strength lower in Sweden where Crab traits more often also seen in Wave than is the case in Spain.
- Phenotypic variation showed even more gradual cline in Spain than genomic. Sweden showed higher phenotypic divergence between ecotypes than Spain, though both in same direction.
- While two regions share many similarities, they also show several important differences suggesting that they are at different stages of the speciation continuum: Spanish closer to completion of speciation.
- Sex determination was on different loci in the two countries, intraspecific variability in genetic determination of sex.
- Size might be a magic trait, especially in Spain where habitat is more patchy and less gradual.
- Completion of speciation involves complex ecological and/or evolutionary dynamics.

Is there evidence that this divergence happened independently in the two regions? Relatively young species, and young Swedish population.
Found low gene flow between overlapping ecotypes in low shore, but I wonder how that looks relative to gene flow between Crab ecotypes at different points on the shore?

# Discussion: Genetic basis of speciation II: Gene regulation

## Chen et al 2024

- Residual sequences of ancient retroviruses influence the adaptive diversification of species by regulating host gene expression.
- ERVs are typically non-coding, having lost most their function over time. However, they still introduce novel genetic material and biological function in hosts. Therefore, acquisition of ERVs may have been adaptive and contributed to the evolution of novel traits.
- In birds, which have generally smaller genomes than near outgroups, estimates of LTR elements of ERV genome have been low. Biological function of solo-LTR poorly known.
- Found higher frequencies of solo-LTR formation (higher efficiency in purging EVE from genome), continuous accumulation of solo-LTR through speciation of Passeriformes (data on transcription expression and population resequencing in zebra finches), 20 genes in zebra finches with lineage-specific solo-LTR differentially expressed cf orthologs in chicken, dual-luciferase reporter assays confirm cis-regulatory activity of solo-LTRs upstream of ITGA2 gene.
- Solo-LTR formation as host defence mechanism or result of high recombination activity among LTRs. Additionally, many solo-LTRs carry regulatory elements and have cis-regulatory function.

## Yusuf et al 2025

(Much more dense and difficult to follow. Simple, interpretive language, guys!)

- Cis-regulation known to influence morphological and physiological RI, but not much known about mate recognition behaviour, specifically about genetic mode of action driving signals and preferences.
- Allele-specific expression differences (differences in expression of gene copies from maternal vs paternal genomes) across conditions. F1 hybrid female neural samples grouped by parental allele, indicating strong cis-regulatory divergence in neural expression patterns between species irrespective of acoustic environment.
- Found extensive, genome-wide CRE divergence related to response to male acoustic sexual signals. (Broad distribution of diverged CR genes across chromosomes, differences in function of genes having context-dependent divergent expression, genomic signatures of divergent selection in allopatry.)
- Notably more CRE divergence in sympatry than allopatry, suggesting that neurogenetic pathways of mate recognition are social context-dependent.

# Discussion: Genome architecture

## Meyer et al 2024

- Large structural variants (SVs) like inversions both establish and maintain divergent haplotypes (and reducing inter-haplotype recombination). 
- Although popular in studies of differentiation (and ecotype formation), still don't know what conditions give rise to inversions, how they are maintained over the long term, and how they contribute to RI and speciation.
- LD can form between multiple distant functional sites, but also between co-adapted gene complexes and deleterious mutations (by chance). So dynamics of inversion can be driven by multiple simultaneous processes.
- Allelic content of inversion can also change over time: new mutations, or gene flux between inverted haplotypes. This can influence the ferquency of an inversion and ultimately the evolutionary trajectory (and contribution to RI).
- N-S lineages in Northeast Atlantic and marine-lagoon lineages in Mediterranean. Strong genetic differences in the same part of the genome, meaning genomic architecture probably relies on shared structural variation.
- Whole-genome resequencing of samples; high-coverage linked-read sequencing for reference genome. PCA on SNPs for population structure. Genetic differentiation (F~ST~), nucleotide diversity ($\pi$), absolute genetic divergence (d~xy~) to characterise genomic landscape of divergence. Ancestral recombination graphs (ARGs) to describe variation in coalescence times across genome using time to the most recent common ancestor (TMRCA); local ancestry for each haplotype within inversion regions.
- Pronounced population structure even in adjacent sampling locations; tight LD. Clustering by geography is only for LD regions, overall clustering seems to be based on chromosomal inversions (three inversion genotypes), suggesting two polymorphic inversions containing large numbers of sites in strong LD. Similarly, genome-wide differentiation is relatively weak, but F~ST~ and d~xy~ values were high in two chromosomes (2, 12). 
- Sufficient time has elapsed since appearance of inverted haplotypes to have mutation-drift equilibrium.
- Origin of inversions: inversions appeared within the lineage with no introgression or gene flow upon secondary contact---instead, incomplete lineage sorting (inversion in B12 is near chromosome extremity), remained polymorphic for long period of time.
- B12 is type 1 (divergent) but B2 involves interaction of Type 1 and Type 2 (within-population variation). B2 inversion is private to Mediterranean lagoons: intermediate haplotype frequencies, heterozygote advantage; because it is longer, more likely to have accumulated deleterious mutations, so polymorphism maintained by pseudo-overdominance.
- B12 might facilitate speciation over the long term, but uncertain whether B2 will undergo differential fixation between habitats or universal fixation of one haplotype.

## Huang et al 2025

- Because inversions tightly link locally adapted alleles, adaptive response is poor when the population encounters a new environment.
- Dunes have low nitrogen levels, low vegetation cover, than surrounding sand sheet. Dune ecotype has larger/heavier seeds.
- Habitat data + genotyping-by-sequencing data --> genotype-environment association (GEA) analyses to test for associations between inversions and shared selective pressures. QTL mapping to identify seed size difference regions. Whole-genome sequences (existing), population genomics to identify selective sweeps shared by two dune ecotypes (do inversions contribute disproportionately to parallel genetic evolution).
- Independent origins of the two dune ecotypes, because SNP PCA yielded geographical clusters of both dune and non-dune. This is despite habitat variables (soil and vegetation) separating between dune and non-dune (PC1).
- Crosses on seed size had F~1~ with intermediate seed size. In F~2~, many genomic regions were overrepresented in large-seeded plants, meaning seed size is highly polygenic.
- QTLs associated with seed size belonged to inversions more likely than not, and more QTL windows were shared than expected by chance in pairs within and between locations.

# Discussion: Introgression

## Jensen et al 2024

- Due to Haldane's rule, gene flow between divergent lineages more likely through homogametic hybrids than heterogametic sex---leading to phylogenetic discordance between autosomes and homogametic sex loci.
- Y chromosome introgression therefore rare, and the few cases reported have mostly been in relatively recently diverged lineages. Related to positive selection and meiotic drive.
- In guenons, which hybridise a lot in the past and present, males disperse after maturation, giving opportunities for introgression across species boundaries. Maternal introgression cases already known in these organisms.
- WGS two guenon species (*Cercopithecus denti*, *C. wolfi*) to add to recent dataset, and resequenced two others. 
- Why compared against rhesus macaque? Why not another species from the same continent, near relative?
- Saw mitonuclear discordance, but Y tree was very similar to species tree, in line with Haldane's rule---except for *C. denti* which in the Y tree was closest to *C. mitis* and not *C. wolfi*. 
- To distinguish between introgression and ILS, compared pairwise nucleotide differences (d~xy~), and found that nucleotide divergence was 3.6 times greater on autosomes than Y (suggesting introgression from *mitis* into *denti*).
- Autosomal gene flow tested using D-statistic, and found overall low levels of allele sharing between *mitis* and *denti*, suggesting that the *mitis*-like Y chromosome in *denti* was initially introduced at a low frequency.
- Then compared neutral (drift) and non-neutral processes using simulations (multi-species-coalescence-with-introgression, MSci). Low initial frequency but selective force allowed fixation. 
- Looked for possible targets of selection in Y-linked genes with amino acid substitutions in the different lineages. Found potential in genes linked to sperm competition.
- Tried to compare adaptive introgression with meiotic drive, but didn't get conclusive results that suggest one over the other.

## Jorquera et al 2025

- Three skua species in S Hemisphere with rather distinct breeding ranges; generalist scavengers and predators. Failure to resolve phylogenetic status/taxonomic relationships of Brown Skua subspecies (ILS, introgression, methodology limitations). 
- Clarified evolutionary history of SH skuas (reconstructing demographic history), revealing timing of diversification and impact of past climate oscillations on effective population size. Then, used SDMs to predict range changes in areas of introgression. 
- Used high-coverage (15x) WGS from 111 skuas in 21 locations, covering entire SH spatial extent of their ranges. 
- Genetic structure and differentiation (using SNPs) suggest three clusters, aligning with current species groups. But also show several admixed populations. Phylogeny and population structure based on nuclear SNPs show 7 phylogeographic groups. 
- Reconstrcuted phylogeny using TreeMix, which suggests gene flow events in the past (not just branching tree).
- D-statistics and f-branch test to distinguish between ILS and introgression.
- Genomic signatures of adaptation using RAiSD and XP-nSL: detect genome-wide selective sweeps that produce regions of reduced genetic diversity near an adaptive mutation. Generally, chromosomes 9 and 18, with broad cellular functions. Strongest differential selection, nearing fixation, associated with growth, reproductive processes, and pigmentation. 
- Specifically, might be related to thermogenic adaptations. Lipid metabolism in Brown Skua, fatty acid degradation and metabolic pathways in SP Skua, glycerolipid metabolism in Chilean. Traits: ability to endure extreme temperatures, prolonged periods without food, various environmental pressures.
- SDMs predict changes for all species, and this will change overlaps and therefore introgression. Balance between disruptive selection and homogenisation via gene flow will determine future genetic differentiation, and future of the species groups. 
- Very weirdly written paper, hotchpotch (flow is poor). Even discussion ends abruptly.

# Discussion: Old variation

(not detailed reads this time)

## Meier et al 2023

- African lake cichlids: largest radiation was in a very young lake, and all ecological guilds evolved in situ through lineage fusion (admixture) and fission (speciation), from several ancestral populations that met.
- LVRS cichlid fishes had a hybrid origin: 2-3 older lineages that had split from common ancestor through geographical isolation
- Should Lake Victoria clades all be considered monophyletic, instead of having same genera across lakes?
- Entire LVRS had hybrid origin between Congolese and Upper Nile lineages. Victoria Radiation formed from hybridisation when lake refilled. Later, hybridisation within VR gave rise to ecological groups and hybrid species with novel trait combinations.
- Syngaemon dynamics similar to metapopulation dynamics.
- Natural hybrids should not be dismissed as detrimental or evolutionary dead-ends.

## Lutgen et al 2025

- Wheatears show high incidence of convergence plumage colour evolution and frequent hybridisation. Same phenotypes reappear multiple times across the genus.
- In *hispanica* complex, throat colour is polymorphic in 3 of 4 species, while mantle/neck colour is recombined by hybridisation.
- Variation in throat and mantle colouration are associated with agouti signalling protein (ASIP) locus
- Combination of new and old/introgressed variation at a single gene. This (complex recombined phenotypes underpinned by monogenic architecture) is rare.
- Recombined phenotypes (due to introgression) in extant hybrid zones may be a source for future phenotypic evolution
- Even if phenotypes at different body parts are monogenic, they can be decoupled
- Transspecific throat colour polymorphism is associated with alternative foraging niches (different N isotope signatures)
- Abundance of genotypic and phenotypic admixture: pervasive hybridisation in the complex
- White-throated individuals prey on insects from narrower and lower trophic level than black-throated. Thus, throat polymorphism is related to trophic niche of prey and thereby foraging strategy.
- White mantle evolved adaptively (selection involved)
- Story: originally, all members of *hispanica* complex had black throat and mantle, then white mantle evolved in *melanoleuca* through upstream mutations fixed by positive selection. Later, new variation introduced white throat in *melanoleuca*, which then introgressed into *hispanica* (along with white mantle, LD) and maintained as balanced polymorphism. In *pleschanka*, introgression introduced white throat but not white mantle (selected against).
- Overall, introgression shuffled plumage colouration and led to convergent evolution.

# Discussion: Microbes and microbiomes

## Wang et al 2021

- Microbiome is a source of phenotypic and evolutionary novelty for hosts, since they can respond more rapidly to new selective pressures and therefore provide fitness benefits. But drastic changes in microbiome can also be problematic, and lead to dysbiosis. 
- *Nasonia vitripennis* grown over 85 generations under subtoxic levels of atrazine herbicide(!), and monitored both microbiome composition and function, and host physiology and genetic differentiation.
- 16S rRNA gene amplicon sequencing of microbiome of two wasp populations over 85 generations, for genetic divergence. 
- qPCR for monitoring bacterial density.
- After 24 generations, both groups split into two subpopulations then fed opposite diets. 
- Exposure mediated adaptive changes within the microbiome (efficient metabolism of atrazine) leading to resistance, lasting for more than 11 generations after removal of atrazine.
- Untargeted metabolomic analysis by LC-MS, to understand how exactly microbiome mediated host resistance to atrazine. Found that hosts with the evolved microbiome more efficiently detoxified atrazine. 
- F~ST~ different in two populations, suggesting gradual genetic divergence, and this was corroborated by ADMIXTURE plot which identified two clusters.
- Immune challenge experiments, to test host immunity differences: heat-inactivated bacteria into wasp pupae, then used proportion of eclosed adults in 120 h as inverse measure of immune activation (induced response would channel energy away from metamorphosis). 
- Also induced selective pressure on host genome (altered gene expression and immune response). Both host and microbiome adapted, either independently or in synergy.
- Microbiome transplants to test compatibility without coadaptation. Found an asymmetric host genome--microbiome incompatibility, suggesting that coadaptation was necessary for host to tolerate new microbiome which in turn might have resulted in differential expression and fixation of specific host genes involved in microbiome regulation.
- Throughout, comparisons with germ-free groups helped attribute differences to microbiome.
- They identified signatures of selection and adaptation in holobiont and hologenome, at the physiological, transcriptional and genomic levels.
- Selection may act at multiple levels on any organism: on the host, on the microbiome, or on both in synergy. This means host-microbiome equilibrium is important and changes with adaptation.

## Baiz et al 2024

- What happens to diverged host microbiomes when host populations come in secondary contact?
    - Extension of DMI: intimate host-bactera relationships could mean deleterious combinations or incompatible interactions.
    - On the other hand, beneficial mutations can spread via adaptive introgression, and admixture can create opportunities for selection. Intermediate environment in hybrids may allow wider diversity of microbes than each parent alone.
- Syntopic sister taxa, which have diverged mostly in melanin-based and carotenoid-based pigmentation, but hybridise in contact zones.
- Aimed to identify species-specific bacteria, quantify differences in gut microbiome diversity, and test whether admixed individuals exhibit disrupted microbiome diversity and whether microbiome variation is correlated with host admixture.
- 16S amplicon sequencing from faecal samples to quantify gut microbiome diversity (alpha and beta).
- Extent of host admixture was assessed visually using plumage phenotype, which are known to be nearly perfectly correlated, summarised as a 0--1 proportion based on ordinal scores for 9 individual traits.
- ASV abundance was higher in admixed individuals more similar to BWWA, which are more yellow (more carotenoids), suggesting that the ASVs may be linked to carotenoid deposition.
- Overall, found low (but one ASV each) specific-specific divergence in host microbiome, unlike previous study on 15 other warbler species (here, year and locality explained more variation). They speculate that this is due to unique evolutionary history of *Vermivora*: relatively young and high genomic homogenisation due to hybridisation. Or, lack of habitat divergence could overpower species-specific effects.
- GWWA had *Rickettsia* ASV, which showed evidence of additive genetic effects correlated with plumage score, with preference for more GWWA ancestry. On the other hand, BWWA had *Kineococcus* ASV, which is orange and encodes for carotenoid synthesis genes, and seemed to have high affinity for non-admixed BWWAs. Gut microbiome variation (abundance of ASVs) is associated with degree of host admixture.
- But admixed individuals did not host both species-specific parental ASVs, and abundance of some ASVs is correlated with degree of admixture. 
- No sign of dysbiosis.

# Discussion: Macroevolution

## Heuer et al 2024

- Carnivores have extensive colour polymorphism. This is thought to confer several evolutionary advantages, especially in colonising new niches.
- Tested predictions that speciation rates are higher in polymorphic lineages, and their divergence times are more recent, and that within closely related groups the polymorphic lineages are ancestral and monomorphic are dervied.
- They also checked whether greater speciation rates are associated with niche breadth (no. of occupied habitats and range size).
- Used phylogenetic comparative methods using recent Carnivora phylogenetic, time-calibrated supertree. 
- Tip branch lengths compared, then Wilcoxon rank tests and Pearson's contingency coefficients.
- Speciation rates estimated using Diversitree package, with multiple models: binary-state speciation and extinction (BiSSE), HiSSE, QuaSSE, SecSSE.
- Tested niche breadth using Wilcoxon and Kruskal-Wallis tests, then somehow 95% CI and t-test...? PGLMMs with everything as random effect, then R^2^...? All stats are so fishy.
- Branch lengths not significantly different between two; polymorphic carnivores higher speciation rate than monomorphic; niche breadth not important.
- Other selective forces like predator-prey coevolution could be at play. (Suggestions of pleiotropy.)
- Suggest that polymorphism could facilitate sympatric speciation via temporal niche segregation or assortative mating.

## Title et al 2024

- Evolution of snakes within scaled reptiles is interesting, because distinct from lizards in several ways.
- Simpsonian macroevolution is when major biodiversity expansions occur through qualitative phase shifts into new adaptive zones, and snakes potentially align with this.
- These phase shifts can be considered as singularities: rapid changes along many axes that appear to have been instantaneous at geological time scales, but also those that are unpredictable from prior states.
- Authors explored the role of such phenotypic shifts in the evolutionary diversification of squamate reptiles.
- Combined their own sequenced phylogeny with GenBank, then time-calibrated the species-level dated phylogenomic tree. 
- Traits obtained from literature and museum specimens.
- Index of net innovation, absolute difference in phenotype between focal species and (inferred) ancestral state, separate for each trait. Another index of absolute branch-specific change along branches.
- TR statistic similar to diversification rate, ordination to identify nodes best explaining species-level phenotypic variation.
- Snakes have undergone major phenotypic transformations, and have much higher net innovation rates than lizards. This means the origin or early stages of snakes saw massive shifts in traits for feeding, locomotion, sensing; much of the phenotypic variation explained by one singular event early on.
- Morphological evolution mirrored by ecological trait diversification: trophic niche evolution and diet divergence.
- Overall, snakes cover wider dietary breadth than lizards, including aquatic and semiaquatic prey. However, diets of individual snake species are narrower than those of lizard species. Snakes also feed much less than lizards on adults of insects.
- While morphology and diet seem to have diverged in snakes from lizards, climatic niche and life history haven't changed much.
- Snakes show higher speciation rates than lizards (CLaDS, BAMM), but this is not linked to richness or individual traits. In latter case, potential statistical confound with the singularity at the origin of snakes and the most successful Colubriformes radiation.
- Snakes are an ongoing radiation characterised by sustained ecological and species (adaptive) diversification, earlier on triggered by one or more singular events.
- Importance of dramatic shifts in tempo and mode; extrapolating contemporary microevolution through geological time may not give us the right answers.