---
title: "Prezygotic isolation"
bibliography: "../biol7117-speciation.json"
csl: "../evolution.csl"
format: 
  docx:
    reference-doc: "../word_template.docx"
    number-sections: false
    output-file: "Thrikkadeeri_Long02_Prezygotic-Isolation.docx"
---

Word count (koRpus): 782

# Summary

Prezygotic isolation comprises various ecological and sexual isolation mechanisms, such as habitat selection and morphological trait divergence. Studies of ecological isolation have mostly explored the early stages of speciation, and those of geography in particular have been limited to species pairs lacking divergent characteristics. In contrast, how divergent ecology and geography synergistically affect reproductive isolation (RI) later in speciation has been relatively unexplored. Sexual selection, on the other hand, has been explored using associations between either genomic divergence and sexual traits, or sexual traits and RI, but not using the complete mechanistic pathway from genomic divergence to sexual traits to barriers to gene flow. These tests require systems having both appropriate ecologies and relatively well understood genetics, which have historically been rare. However, @zhang2024 and @schield2024 used two such model systems, and attempted to bridge some of these knowledge gaps.

@zhang2024 used three *Belonocnema* gall wasp species, which show specificity to *Quercus* hosts. Two species pairs are in allopatry, while species in the third are sympatric and are known to be in the later stages of speciation. The authors asked two main questions: first, whether host plant divergence (ecological isolation) results in higher RI for allopatric lineages; and second, whether sympatry causes higher RI than allopatry under existing ecological isolation. Using adult wasps (after balancing phenological differences using cold storage of galls), they conducted two experiments, both involving introduction of the wasp into a container. First, they measured host plant selection of only females using a controlled two-choice experiment, inferring oviposition decision from time spent on the host plant. For this measure, they calculated both the proportion of time spent as well as pairwise estimates of difference in host plant preference. In the second experiment, they measured sexual isolation by observing courtship and mating interactions between the two sexes, using controlled no-choice preference trials, calculating both a probability of mating between various species pairs, as well as pairwise strengths of sexual isolation. 

@schield2024 focused on Barn Swallow (*Hirundo rustica*), a clade early in the speciation process (most recent divergence around 11 kya). It has a large Holarctic distribution with multiple populations (six subspecies) under strong divergent sexual selection via plumage traits like breast feather colour and tail streamer length. It also has multiple hybrid zones with divergence in both sexual traits and non-breeding migratory route (ecological trait). To understand the genomic underpinnings of divergent sexual selection driving RI, the authors undertook extensive sampling across the entire species range, covering both allopatric and sympatric (hybrid) zones, and collecting both genetic and morphological data. Their main analyses involved trait loci--background loci comparisons of genetic differentiation (F~ST~) of allopatric populations, of geographic and genomic clines across hybrid zones, and of interchromosomal linkage disequilibrium (LD) across all populations.

@zhang2024 found that habitat preferences and geographic context together drive ecological isolation, and thereby divergent selection, in *Belonocnema* wasps. Highest levels of both habitat and sexual isolation were seen in sympatric wasps having different host plants, whereas lowest levels were in allopatric species with a shared host plant---suggesting selection for reduced migration and hybridisation. Further, the relative strengths of habitat and sexual isolation in allopatric species with a shared host plant were asymmetric: the lineage with greater emigration showed stronger habitat isolation (selection for reduced migration) while that with greater immigration showed stronger sexual isolation (selection for reduced hybridisation). 

@schield2024 found that both plumage trait values and admixture proportions of Barn Swallows from hybrid zones were intermediate or similar to those of parental lineages. Moreover, trait variation was controlled by a few select loci, and breast feather colour was even associated with the sex chromosome (Z), making them conducive to coupling and divergent positive sexual selection. Thus, LD arose from admixture during hybridisation after allopatry, and crucially, was maintained upon secondary contact by selection, which worked by slowing erosion of LD rather than enhancing LD beyond starting levels. Across all analyses, they consistently found strongest differentiation of ssp. *rustica*, and weakest patterns in the *tytleri*-*gutturalis* hybrid zone---which highlights the importance of the migratory divide (ecological isolation) in driving RI.

Together, these studies show that both ecological and sexual mechanisms often work in tandem to drive prezygotic isolation, and highlight that these mechanisms are not mutually exclusive. @zhang2024 used well-designed experiments, while @schield2024 used extensive sampling and complex analytical techniques. They also did a great job of communicating their numerous results in comprehensive detail yet with clarity. The *Belonocnema* wasps and Barn Swallow both represent good models for speciation research, due to their unique ecologies and geographies, and are useful for exploring not just how speciation is initiated but also how it is brought to completion. 

# References