---
title: "Reinforcement"
bibliography: "../biol7117-speciation.json"
csl: "../evolution.csl"
format: 
  docx:
    reference-doc: "../word_template.docx"
    number-sections: false
    output-file: "Thrikkadeeri_Long03_Reinforcement.docx"
---

Word count (koRpus): 767

# Summary

Speciation is known to be initiated by allopatric divergence, but much less is known about how sympatry (secondary contact) drives further reproductive isolation (RI) and thereby completes speciation. RI being fully completed prior to secondary contact is unlikely because this model requires extremely long periods of evolutionary time.
The prevalence of hybrid zones in nature supports an alternative model involving secondary contact with incomplete RI, followed by direct or indirect selection for increased RI in sympatry. Direct selection for instance against maladaptive hybridisation, which is called reinforcement selection, can be driven by reproductive character displacement (RCD) in both prezygotic and postzygotic pathways. 

@bemmels2021 studied the role of sympatry in completing speciation using a pair of sister species of *Empidonax* flycatcher distributed across North America, having an eastern region of broad sympatry and a western contact zone of narrow sympatry. They used blood samples to generate whole genome and genotype sequences, and further explored genomic differentiation. Morphological measurements of birds were combined with spring arrival times from eBird to analyse character displacement, and they also used distribution models for coalescent demographic modelling. On the other hand, @levitan2025 studied gametic isolation in two urchin species able to form F1 embryos, *Strongylocentrotus droebachiensis* and *Mesocentrotus franciscanus*. They tested for conspecific sperm precedence (CSP) using a combination of no-choice and competitive choice (with varying heterospecific sperm ratios) assays, and also tested whether hybrid fertilisation was related to the genetic makeup (allele frequencies) and provenance (ancestral vs derived) of male and female gamete proteins. 

Patterns of genomic differentiation in the *Empidonax* species, explored using weighted Hudson's F~ST~ and proportion of genetic ancestry, were consistently higher in the eastern region of broad sympatry than in the western contact zone. Their coalescent models suggested longer time since secondary contact in the east; in the west, geographical overlap was likely minimal during the last glacial maximum, and continuous gene flow may exist even in the present day. Thus, there was evidence of increased RI following secondary contact in the east, whereas the western population had higher introgression levels. However, they found very weak signals of reproductive character displacement: only one of the several morphological measurements showed statistically significant divergence but this was also a subtle difference in crown colour in the UV range which birds are unlikely to perceive. 

The urchin choice assays revealed that conspecific sperm presence lowered hybridisation fertilisation success, even when sperm ratios favoured the heterospecifics. Much of the individual variation in these CSP results was explained by gamete genotype, with shared (ancestral) alleles in sperm increasing hybridisation success, and shared alleles in eggs being more prevalent in allopatry than in sympatry, potentially relating to greater costs of egg wastage than sperm wastage. 

Both studies indicate greater RI and lower introgression in sympatry, supporting the multistage model of speciation in which the completion of speciation may be facilitated by existing intraspecific variation which then undergoes reinforcement selection. Although both studies explored this same topic of reinforcement, they had a fundamental macro-versus-micro distinction. @bemmels2021 combined traditional genetic analyses with "macro" analytical techniques involving species distribution modelling, demographic modelling and citizen science data, to explore macroevolutionary perspectives. Their combination of analyses was instrumental in estimating geographical and temporal contexts, which are crucial for understanding speciation over geological time scales. @levitan2025 on the other hand explored microevolutionary questions about gametic compatibility using "micro" techniques, delving as far deep as allele differences in gametes. 

While @bemmels2021 found clear differences between regions of broad and narrow sympatry, some of their inferences seemed to confound this dichotomy with that of sympatry vs allopatry. For instance, they relate the higher RI in the east to increased divergence in reproductive traits in sympatry than in allopatry (i.e., RCD). Moreover, their focus seemed limited to prezygotic isolation, and I feel the discussion could have benefitted from more attention to potential postzygotic mechanisms. The paper itself was well written though, unlike @levitan2025 which in my opinion was an example of poor writing. I feel that the paper suffered greatly from dense language and poor section structure---more than it should have given the technical nature of the study. For instance, the full background section on the proteins was a nice touch and important information, but it was missing takeaways in lay language. The lengthy Results section contained things that belong in the Methods such as model and test specifications, and was even longer than the Discussion. And beyond pedantry about language, the paper as a whole reads like an exhaustive report of technical details, and could have benefitted from more inferential or interpretive writing especially in discussing the results.

# References